//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;
namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class Question
    {
        [DataMember]
        public int FileID { get; set; }
        [DataMember]
        public string FileName { get; set; }
        [DataMember]
        public int ExamID { get; set; }
        [DataMember]
        public int Level { get; set; }
        

        public virtual Exam Exam { get; set; }
    }
}
