//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int StudentID { get; set; }
        public int ExamID { get; set; }
        public Nullable<double> Level1_Score { get; set; }
        public Nullable<double> Level2_Score { get; set; }
        public Nullable<double> Level3_Score { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
