//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;
namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        
        public Student()
        {
            this.Reports = new HashSet<Report>();
        }
        [DataMember]
        public int StudentID { get; set; }
        [DataMember]
        public string StudentName { get; set; }
        [DataMember]
        public System.DateTime DOB { get; set; }
        [DataMember]
        public string Mobile_Num { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Pwd { get; set; }
        [DataMember]
        public string City { get; set; }
        [DataMember]
        public string State { get; set; }
        [DataMember]
        public string Qualification { get; set; }
        [DataMember]
        public string College { get; set; }
        [DataMember]
        public int Year_of_Completion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
